package com.github.eztang00.firstandroidgame.gamephysics;

import java.util.Objects;

/**
 * Very simple class representing an (x, y)
 * Similar to Android's Point or PointF classes, except double
 */
public class DoublePoint {
    public double x;
    public double y;

    public DoublePoint(double x, double y) {
        this.x = x;
        this.y = y;
    }

    public DoublePoint(DoublePoint src) {
        this.x = src.x;
        this.y = src.y;
    }

    @Override
    public boolean equals(Object o) {
        // Generated by Android Studio
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DoublePoint that = (DoublePoint) o;
        return Double.compare(that.x, x) == 0 && Double.compare(that.y, y) == 0;
    }

    @Override
    public int hashCode() {
        // Generated by Android Studio
        return Objects.hash(x, y);
    }
}
